apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insecure-member-api.fullname" . }}
  labels:
    {{- include "insecure-member-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "insecure-member-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "insecure-member-api.name" . }}
    spec:
      serviceAccountName: {{ include "insecure-member-api.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      containers:
        - name: member-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_HOST
              value: {{ .Values.database.host | quote }}
            - name: DATABASE_USERNAME
              value: {{ .Values.database.username | quote }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "insecure-member-api.fullname" . }}-db
                  key: password
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            privileged: {{ .Values.securityContext.privileged }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: http
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
