{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "insecure-member-api.fullname" . }}
  labels:
    {{- include "insecure-member-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "insecure-member-api.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
{{- end }}
