apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: legacy-importer-tls
  labels:
    app: legacy-importer
spec:
  secretName: {{ .Values.certificate.secretName }}
  duration: {{ .Values.certificate.duration }}
  dnsNames:
    - {{ .Values.certificate.dnsName }}
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: ClusterIssuer
