apiVersion: v1
kind: Secret
metadata:
  name: legacy-importer-db
  labels:
    app: legacy-importer
type: Opaque
stringData:
  username: {{ .Values.database.user }}
  password: {{ .Values.database.password }}
  connection-string: "Host={{ .Values.database.host }};Username={{ .Values.database.user }};Password={{ .Values.database.password }}"
