{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "batch-report.serviceAccountName" . }}
  labels:
    {{- include "batch-report.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
