using System.Text;

namespace ChartPilot.Core.Reporting;

/// <summary>Inputs for the generated deploy workflow.</summary>
/// <param name="ChartPath">The chart path as it appears in the repository, i.e. <c>./chart</c>.</param>
/// <param name="ChartName">The release name used by <c>helm template</c> and <c>helm upgrade</c>.</param>
/// <param name="Environments">The environments offered by the workflow_dispatch choice input.</param>
/// <param name="ProfileId">The golden path profile the validate job checks against.</param>
/// <param name="FailOn">info, warning or critical — the severity that fails the build.</param>
/// <param name="Namespace">The namespace <c>helm upgrade --install</c> deploys into.</param>
public sealed record WorkflowOptions(
    string ChartPath,
    string ChartName,
    IReadOnlyList<string> Environments,
    string ProfileId,
    string FailOn,
    string Namespace);

/// <summary>Generates the CI workflow that runs the same review the GUI just ran.</summary>
public interface IWorkflowGenerator
{
    string Generate(WorkflowOptions options);
}

/// <summary>
/// Emits a GitHub Actions workflow as text rather than through a YAML serializer: a serializer
/// would quote or mangle the <c>${{ }}</c> expressions, which have to survive verbatim.
/// </summary>
public sealed class GitHubActionsWorkflowGenerator : IWorkflowGenerator
{
    private const string Nl = "\n";
    private const string EnvExpression = "${{ inputs.environment }}";

    private static readonly IReadOnlyList<string> DefaultEnvironments = ["dev", "test", "prod"];
    private static readonly IReadOnlySet<string> FailOnLevels =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "info", "warning", "critical" };

    public string Generate(WorkflowOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        var chartPath = NormalizePath(options.ChartPath);
        var chartName = Fallback(options.ChartName, "release");
        var profileId = Fallback(options.ProfileId, "default");
        var failOn = NormalizeFailOn(options.FailOn);
        var ns = Fallback(options.Namespace, "default");
        var environments = NormalizeEnvironments(options.Environments);
        var valuesFile = $"values-{EnvExpression}.yaml";

        var sb = new StringBuilder();

        sb.Append("# Generated by ChartPilot.").Append(Nl);
        sb.Append("name: Helm Deploy").Append(Nl);
        sb.Append(Nl);
        sb.Append("on:").Append(Nl);
        sb.Append("  workflow_dispatch:").Append(Nl);
        sb.Append("    inputs:").Append(Nl);
        sb.Append("      environment:").Append(Nl);
        sb.Append("        description: Environment to validate and deploy").Append(Nl);
        sb.Append("        required: true").Append(Nl);
        sb.Append("        type: choice").Append(Nl);
        sb.Append("        options:").Append(Nl);

        foreach (var environment in environments)
        {
            sb.Append("          - ").Append(environment).Append(Nl);
        }

        sb.Append(Nl);
        sb.Append("jobs:").Append(Nl);
        sb.Append("  validate:").Append(Nl);
        sb.Append("    name: Validate chart").Append(Nl);
        sb.Append("    runs-on: ubuntu-latest").Append(Nl);
        sb.Append("    steps:").Append(Nl);
        sb.Append("      - uses: actions/checkout@v4").Append(Nl);
        sb.Append("      - name: Helm lint").Append(Nl);
        sb.Append("        run: helm lint ").Append(chartPath).Append(Nl);
        sb.Append("      - name: Render manifests").Append(Nl);
        sb.Append("        run: helm template ").Append(chartName).Append(' ').Append(chartPath)
          .Append(" -f ").Append(valuesFile).Append(Nl);
        sb.Append("      - name: Run platform checks").Append(Nl);
        sb.Append("        run: chartpilot check ").Append(chartPath)
          .Append(" -f ").Append(valuesFile)
          .Append(" --profile ").Append(profileId)
          .Append(" --fail-on ").Append(failOn).Append(Nl);
        sb.Append(Nl);
        sb.Append("  deploy:").Append(Nl);
        sb.Append("    name: Deploy").Append(Nl);
        sb.Append("    needs: validate").Append(Nl);
        sb.Append("    runs-on: ubuntu-latest").Append(Nl);
        sb.Append("    environment: ").Append(EnvExpression).Append(Nl);
        sb.Append("    steps:").Append(Nl);
        sb.Append("      - uses: actions/checkout@v4").Append(Nl);
        sb.Append("      - name: Deploy with Helm").Append(Nl);
        sb.Append("        run: |").Append(Nl);
        sb.Append("          helm upgrade --install ").Append(chartName).Append(' ').Append(chartPath).Append(" \\").Append(Nl);
        sb.Append("            -f ").Append(valuesFile).Append(" \\").Append(Nl);
        sb.Append("            --namespace ").Append(ns).Append(" \\").Append(Nl);
        sb.Append("            --create-namespace").Append(Nl);

        return sb.ToString();
    }

    private static IReadOnlyList<string> NormalizeEnvironments(IReadOnlyList<string>? environments)
    {
        if (environments is null)
        {
            return DefaultEnvironments;
        }

        var result = new List<string>(environments.Count);
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var environment in environments)
        {
            if (string.IsNullOrWhiteSpace(environment))
            {
                continue;
            }

            var trimmed = environment.Trim();

            if (seen.Add(trimmed))
            {
                result.Add(trimmed);
            }
        }

        // A workflow_dispatch choice input with no options is invalid YAML for Actions, so an empty
        // environment list falls back to the conventional three.
        return result.Count == 0 ? DefaultEnvironments : result;
    }

    private static string NormalizeFailOn(string? failOn)
    {
        var trimmed = failOn?.Trim();

        return !string.IsNullOrEmpty(trimmed) && FailOnLevels.Contains(trimmed)
            ? trimmed.ToLowerInvariant()
            : "critical";
    }

    private static string NormalizePath(string? path)
    {
        var trimmed = path?.Trim();

        if (string.IsNullOrEmpty(trimmed))
        {
            return "./chart";
        }

        trimmed = trimmed.Replace('\\', '/');

        return trimmed.StartsWith("./", StringComparison.Ordinal) ||
               trimmed.StartsWith('/') ||
               trimmed.StartsWith("../", StringComparison.Ordinal)
            ? trimmed
            : "./" + trimmed;
    }

    private static string Fallback(string? value, string fallback)
        => string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();
}
