{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "member-api.fullname" . }}
  labels:
    {{- include "member-api.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.istio.gateway.host | quote }}
  gateways:
    - {{ .Values.istio.gateway.name }}
  http:
    - match:
        - uri:
            prefix: /api/members
      route:
        - destination:
            host: {{ include "member-api.fullname" . }}
            port:
              number: {{ .Values.service.port }}
      timeout: {{ .Values.istio.virtualService.timeout }}
      retries:
        attempts: {{ .Values.istio.virtualService.retries.attempts }}
        perTryTimeout: {{ .Values.istio.virtualService.retries.perTryTimeout }}
        retryOn: gateway-error,connect-failure,refused-stream
{{- end }}
